# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-12-23 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191222_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
