# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-12-25 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_purchaseproduct_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprintersetting',
            name='printerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.PrinterSetting'),
        ),
    ]
