# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-12-25 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
