# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-12-25 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_invoice_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='invoiceActualNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='invoiceSeriesID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Invoice'),
        ),
    ]
