# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-01-25 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200113_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warningStockLimit',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='buyersOrderNumber',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='deliveryNote',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='dispatchDocumentNumber',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='dispatchNoteDate',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='dispatchThrough',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='otherCharges',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='otherReference',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='roundOff',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supplierReference',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='paidAgainstBill',
        ),
        migrations.AlterField(
            model_name='sales',
            name='customerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Supplier'),
        ),
    ]
